### model

model_name_or_path: /data1/pretrained/bioclip/models/Qwen2.5-VL-7B
stage: sft
do_train: true
finetuning_type: lora
dataset: bioreason_source_b # 联合训练 [cite: 366]
template: qwen2_vl

### output
output_dir: saves/bioreason/sft_only_b
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0 # 根据论文建议设置为 2-3 个 epoch [cite: 284]
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
